#!/bin/bash

DOCKER_REPOSITORY=$1
DOCKER_IMAGE_NAME=$2
DOCKER_CONTAINER_NAME=$3
SPRING_PROFILE=$4
MYSQL_ROOT_PASSWORD=$5

echo "DOCKER_REPOSITORY=${DOCKER_REPOSITORY}"
sed -i "s/DOCKER_REPOSITORY=/DOCKER_REPOSITORY=${DOCKER_REPOSITORY}/g" .env
echo "DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAME}"
sed -i "s/DOCKER_IMAGE_NAME=/DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAME}/g" .env
echo "DOCKER_CONTAINER_NAME=${DOCKER_CONTAINER_NAME}"
sed -i "s/DOCKER_CONTAINER_NAME=/DOCKER_CONTAINER_NAME=${DOCKER_CONTAINER_NAME}/g" .env
echo "SPRING_PROFILE=${SPRING_PROFILE}"
sed -i "s/SPRING_PROFILE=/SPRING_PROFILE=${SPRING_PROFILE}/g" .env
echo "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
sed -i "s/MYSQL_ROOT_PASSWORD=/MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}/g" .env

#docker-compose -f docker-compose.yml pull spring_app

docker rm -f "${DOCKER_CONTAINER_NAME}"
docker-compose up -d
docker system prune --force